### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by Annakan** [collective/mr.bob#49]
On windows at least, trying to activate mrbob from an url fail with a I/O error 13, permission denied from urlretrieve in configurator.py / parse_template.

The reason is that urlretrieve expect to open in write mode the file name passed in and fail since tempfile.NamedTemporaryFile already did that.

it seems that (temp_file_name, heasers)= urlretrieve(url) is enough to get a tempfile with the downloaded content in it. (from http://docs.python.org/2/library/urllib.html)

Something like this seems to do the job

``` python
(temp_file_name, _ )= urlretrieve(url)
if not is_zipfile(temp_file_name):
    raise ConfigurationError("Not a zip file: %s" % temp_file_name)
zf = ZipFile(temp_file_name)
try:
   path = tempfile.mkdtemp()
   zf.extractall(path)
   return os.path.join(path, subpath), True
finally:
    zf.close()
```

**Comment by iandennismiller** [comment]
I'm curious what the status of this issue is.  This has become a blocker for Windows compatibility.

It looks to me like the `configurator.py` hack is workable in practical application.  What is the likelihood that tweak can be mainlined?

**Comment by pbauer** [comment]
@iandennismiller as far as I know there are no more problems with windows. At least I know that people use the plone-templates in https://github.com/plone/bobtemplates.plone with windows.

**Comment by iandennismiller** [comment]
I can report that `resolve_dotted_path()` in mr.bob==0.1.2 still has the same issue with fully-qualified Windows paths that include a colon as part of a disk drive - e.g. `C:\`.  This ultimately throws `ModuleNotFoundError: No module named 'C'`, where C is just the drive letter being parsed by mr.bob as a python module. 

```
mrbob C:\Users\idm\test-template
```

```
Traceback (most recent call last):
  File "C:\Users\idm\Envs\testing\Scripts\mrbob-script.py", line 11, in <module>
    load_entry_point('mr.bob==0.1.2', 'console_scripts', 'mrbob')()
  File "c:\users\idm\envs\testing\lib\site-packages\mr.bob-0.1.2-py3.6.egg\mrbob\cli.py", line 162, in main
    defaults=defaults)
  File "c:\users\idm\envs\testing\lib\site-packages\mr.bob-0.1.2-py3.6.egg\mrbob\configurator.py", line 138, in __init__
    self.template_dir, self.is_tempdir = parse_template(template)
  File "c:\users\idm\envs\testing\lib\site-packages\mr.bob-0.1.2-py3.6.egg\mrbob\configurator.py", line 92, in parse_template
    path = resolve_dotted_path(template_name)
  File "c:\users\idm\envs\testing\lib\site-packages\mr.bob-0.1.2-py3.6.egg\mrbob\configurator.py", line 39, in resolve_dotted_path
    module = import_module(module_name)
  File "c:\users\idm\envs\testing\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'C'
```

We are making this work by using a relative pathname, so it's no longer a blocker on Windows for us.  However, I wanted to follow up to let you know the Windows `resolve_dotted_path()` problem still persists with full Windows paths.

**Comment by domenkozar** [comment]
I would accept a PR that asserts `:` is not the second letter in the resolvable name. I'd assume no one has one char modules.
