### ISSUE TITLE
Failed building wheel for mr.bob

### ISSUE THREAD

**Issue by devsetgo** [collective/mr.bob#84]
Hello,

Not sure what the error is, since I am pretty new to Python. I am getting the following error when installing mrbob (pip install mr.bob). I am using Windows 10, python 3.5.2, and pip 9.0.1. 

Let me know if you need anything else or if this is a newbie issue. I was trying to install Flask-Diamond to walk through the tutorials originally when I got this error, then I just tried to install mr.bob from pip to see if that was issue and got the below error.

Thanks, 

C:\Users\mrstu>pip install mr.bob
Collecting mr.bob
  Using cached mr.bob-0.1.2.tar.gz
Requirement already satisfied: setuptools in c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages (from mr.bob)
Requirement already satisfied: six>=1.2.0 in c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages (from mr.bob)
Requirement already satisfied: Jinja2>=2.5.0 in c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages (from mr.bob)
Requirement already satisfied: MarkupSafe in c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages (from Jinja2>=2.5.0->mr.bob)
Building wheels for collected packages: mr.bob
  Running setup.py bdist_wheel for mr.bob ... error
  Complete output from command c:\users\mrstu\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mrstu\\AppData\\Local\\Temp\\pip-build-0nmkyinp\\mr.bob\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\mrstu\AppData\Local\Temp\tmpxrxv5ebkpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\mrbob
  copying mrbob\bobexceptions.py -> build\lib\mrbob
  copying mrbob\cli.py -> build\lib\mrbob
  copying mrbob\configurator.py -> build\lib\mrbob
  copying mrbob\hooks.py -> build\lib\mrbob
  copying mrbob\parsing.py -> build\lib\mrbob
  copying mrbob\rendering.py -> build\lib\mrbob
  copying mrbob\__init__.py -> build\lib\mrbob
  creating build\lib\mrbob\tests
  copying mrbob\tests\test_cli.py -> build\lib\mrbob\tests
  copying mrbob\tests\test_configurator.py -> build\lib\mrbob\tests
  copying mrbob\tests\test_hooks.py -> build\lib\mrbob\tests
  copying mrbob\tests\test_parsing.py -> build\lib\mrbob\tests
  copying mrbob\tests\test_rendering.py -> build\lib\mrbob\tests
  copying mrbob\tests\__init__.py -> build\lib\mrbob\tests
  running egg_info
  writing top-level names to mr.bob.egg-info\top_level.txt
  writing requirements to mr.bob.egg-info\requires.txt
  writing entry points to mr.bob.egg-info\entry_points.txt
  writing mr.bob.egg-info\PKG-INFO
  writing dependency_links to mr.bob.egg-info\dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'mr.bob.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'mr.bob.egg-info\SOURCES.txt'
  creating build\lib\mrbob\template_sample
  copying mrbob\template_sample\.mrbob.ini -> build\lib\mrbob\template_sample
  copying mrbob\template_sample\sample.txt.bob -> build\lib\mrbob\template_sample
  creating build\lib\mrbob\template_starter
  copying mrbob\template_starter\.mrbob.ini -> build\lib\mrbob\template_starter
  copying mrbob\template_starter\sample.txt.bob -> build\lib\mrbob\template_starter
  copying mrbob\tests\example.ini -> build\lib\mrbob\tests
  copying mrbob\tests\example2.ini -> build\lib\mrbob\tests
  copying mrbob\tests\example3.ini -> build\lib\mrbob\tests
  copying mrbob\tests\example4.ini -> build\lib\mrbob\tests
  copying mrbob\tests\example5.ini -> build\lib\mrbob\tests
  copying mrbob\tests\example6.ini -> build\lib\mrbob\tests
  copying mrbob\tests\ignored.ini -> build\lib\mrbob\tests
  copying mrbob\tests\ignored_dirs.ini -> build\lib\mrbob\tests
  copying mrbob\tests\question_order.ini -> build\lib\mrbob\tests
  copying mrbob\tests\unbound.ini -> build\lib\mrbob\tests
  creating build\lib\mrbob\tests\templates
  copying mrbob\tests\templates\strict_undefined.bob -> build\lib\mrbob\tests\templates
  creating build\lib\mrbob\tests\templates\ask_hooks
  copying mrbob\tests\templates\ask_hooks\.mrbob.ini -> build\lib\mrbob\tests\templates\ask_hooks
  creating build\lib\mrbob\tests\templates\ds_store
  copying mrbob\tests\templates\ds_store\.DS_Store -> build\lib\mrbob\tests\templates\ds_store
  copying mrbob\tests\templates\ds_store\.mrbob.ini -> build\lib\mrbob\tests\templates\ds_store
  creating build\lib\mrbob\tests\templates\empty
  copying mrbob\tests\templates\empty\.mrbob.ini -> build\lib\mrbob\tests\templates\empty
  creating build\lib\mrbob\tests\templates\empty2
  copying mrbob\tests\templates\empty2\.mrbob.ini -> build\lib\mrbob\tests\templates\empty2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\mrstu\AppData\Local\Temp\pip-build-0nmkyinp\mr.bob\setup.py", line 79, in <module>
      zip_safe=False,
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages\wheel\bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\build_py.py", line 52, in run
      self.build_package_data()
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\build_py.py", line 110, in build_package_data
      self.mkpath(os.path.dirname(target))
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 339, in mkpath
      dir_util.mkpath(name, mode, dry_run=self.dry_run)
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dir_util.py", line 66, in mkpath
      log.info("creating %s", head)
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\log.py", line 44, in info
      self._log(INFO, msg, args)
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\log.py", line 34, in _log
      stream.write('%s\n' % msg)
    File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\encodings\cp1252.py", line 19, in encode
      return codecs.charmap_encode(input,self.errors,encoding_table)[0]
  UnicodeEncodeError: 'charmap' codec can't encode character '\u030c' in position 50: character maps to <undefined>

  ----------------------------------------
  Failed building wheel for mr.bob
  Running setup.py clean for mr.bob
Failed to build mr.bob
Installing collected packages: mr.bob
  Running setup.py install for mr.bob ... error
    Complete output from command c:\users\mrstu\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mrstu\\AppData\\Local\\Temp\\pip-build-0nmkyinp\\mr.bob\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mrstu\AppData\Local\Temp\pip-qhncuzfq-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\mrbob
    copying mrbob\bobexceptions.py -> build\lib\mrbob
    copying mrbob\cli.py -> build\lib\mrbob
    copying mrbob\configurator.py -> build\lib\mrbob
    copying mrbob\hooks.py -> build\lib\mrbob
    copying mrbob\parsing.py -> build\lib\mrbob
    copying mrbob\rendering.py -> build\lib\mrbob
    copying mrbob\__init__.py -> build\lib\mrbob
    creating build\lib\mrbob\tests
    copying mrbob\tests\test_cli.py -> build\lib\mrbob\tests
    copying mrbob\tests\test_configurator.py -> build\lib\mrbob\tests
    copying mrbob\tests\test_hooks.py -> build\lib\mrbob\tests
    copying mrbob\tests\test_parsing.py -> build\lib\mrbob\tests
    copying mrbob\tests\test_rendering.py -> build\lib\mrbob\tests
    copying mrbob\tests\__init__.py -> build\lib\mrbob\tests
    running egg_info
    writing dependency_links to mr.bob.egg-info\dependency_links.txt
    writing entry points to mr.bob.egg-info\entry_points.txt
    writing requirements to mr.bob.egg-info\requires.txt
    writing mr.bob.egg-info\PKG-INFO
    writing top-level names to mr.bob.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'mr.bob.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mr.bob.egg-info\SOURCES.txt'
    creating build\lib\mrbob\template_sample
    copying mrbob\template_sample\.mrbob.ini -> build\lib\mrbob\template_sample
    copying mrbob\template_sample\sample.txt.bob -> build\lib\mrbob\template_sample
    creating build\lib\mrbob\template_starter
    copying mrbob\template_starter\.mrbob.ini -> build\lib\mrbob\template_starter
    copying mrbob\template_starter\sample.txt.bob -> build\lib\mrbob\template_starter
    copying mrbob\tests\example.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example2.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example3.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example4.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example5.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example6.ini -> build\lib\mrbob\tests
    copying mrbob\tests\ignored.ini -> build\lib\mrbob\tests
    copying mrbob\tests\ignored_dirs.ini -> build\lib\mrbob\tests
    copying mrbob\tests\question_order.ini -> build\lib\mrbob\tests
    copying mrbob\tests\unbound.ini -> build\lib\mrbob\tests
    creating build\lib\mrbob\tests\templates
    copying mrbob\tests\templates\strict_undefined.bob -> build\lib\mrbob\tests\templates
    creating build\lib\mrbob\tests\templates\ask_hooks
    copying mrbob\tests\templates\ask_hooks\.mrbob.ini -> build\lib\mrbob\tests\templates\ask_hooks
    creating build\lib\mrbob\tests\templates\ds_store
    copying mrbob\tests\templates\ds_store\.DS_Store -> build\lib\mrbob\tests\templates\ds_store
    copying mrbob\tests\templates\ds_store\.mrbob.ini -> build\lib\mrbob\tests\templates\ds_store
    creating build\lib\mrbob\tests\templates\empty
    copying mrbob\tests\templates\empty\.mrbob.ini -> build\lib\mrbob\tests\templates\empty
    creating build\lib\mrbob\tests\templates\empty2
    copying mrbob\tests\templates\empty2\.mrbob.ini -> build\lib\mrbob\tests\templates\empty2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mrstu\AppData\Local\Temp\pip-build-0nmkyinp\mr.bob\setup.py", line 79, in <module>
        zip_safe=False,
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\build_py.py", line 52, in run
        self.build_package_data()
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\build_py.py", line 110, in build_package_data
        self.mkpath(os.path.dirname(target))
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 339, in mkpath
        dir_util.mkpath(name, mode, dry_run=self.dry_run)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\dir_util.py", line 66, in mkpath
        log.info("creating %s", head)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\log.py", line 44, in info
        self._log(INFO, msg, args)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\distutils\log.py", line 34, in _log
        stream.write('%s\n' % msg)
      File "c:\users\mrstu\appdata\local\programs\python\python35-32\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u030c' in position 50: character maps to <undefined>

    ----------------------------------------
Command "c:\users\mrstu\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mrstu\\AppData\\Local\\Temp\\pip-build-0nmkyinp\\mr.bob\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mrstu\AppData\Local\Temp\pip-qhncuzfq-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\mrstu\AppData\Local\Temp\pip-build-0nmkyinp\mr.bob\

[mrbobError.txt](https://github.com/domenkozar/mr.bob/files/706671/mrbobError.txt)

**Comment by MikeRyan56** [comment]
Found that Mr.Bob will install with Easy_Install. Not sure why....
