### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u030c' in position 50: character maps to <undefined>

### ISSUE THREAD

**Issue by krl91** [collective/mr.bob#86]
hello,
I try to install mr.bob on Windows 10 with python 3.6.4 and 3.6.3 but it doen't work:

`pip3 install mr.bob
Collecting mr.bob
  Using cached mr.bob-0.1.2.tar.gz
Requirement already satisfied: setuptools in c:\users\krl91\appdata\local\programs\python\python36-32\lib\site-packages (from mr.bob)
Requirement already satisfied: six>=1.2.0 in c:\users\krl91\appdata\local\programs\python\python36-32\lib\site-packages (from mr.bob)
Requirement already satisfied: Jinja2>=2.5.0 in c:\users\krl91\appdata\local\programs\python\python36-32\lib\site-packages (from mr.bob)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\krl91\appdata\local\programs\python\python36-32\lib\site-packages (from Jinja2>=2.5.0->mr.bob)
Installing collected packages: mr.bob
  Running setup.py install for mr.bob ... error
    Complete output from command c:\users\krl91\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\krl91\\AppData\\Local\\Temp\\pip-build-exg5brph\\mr.bob\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\krl91\AppData\Local\Temp\pip-3wr9ewbx-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\mrbob
    copying mrbob\bobexceptions.py -> build\lib\mrbob
    copying mrbob\cli.py -> build\lib\mrbob
    copying mrbob\configurator.py -> build\lib\mrbob
    copying mrbob\hooks.py -> build\lib\mrbob
    copying mrbob\parsing.py -> build\lib\mrbob
    copying mrbob\rendering.py -> build\lib\mrbob
    copying mrbob\__init__.py -> build\lib\mrbob
    creating build\lib\mrbob\tests
    copying mrbob\tests\test_cli.py -> build\lib\mrbob\tests
    copying mrbob\tests\test_configurator.py -> build\lib\mrbob\tests
    copying mrbob\tests\test_hooks.py -> build\lib\mrbob\tests
    copying mrbob\tests\test_parsing.py -> build\lib\mrbob\tests
    copying mrbob\tests\test_rendering.py -> build\lib\mrbob\tests
    copying mrbob\tests\__init__.py -> build\lib\mrbob\tests
    running egg_info
    writing mr.bob.egg-info\PKG-INFO
    writing dependency_links to mr.bob.egg-info\dependency_links.txt
    writing entry points to mr.bob.egg-info\entry_points.txt
    writing requirements to mr.bob.egg-info\requires.txt
    writing top-level names to mr.bob.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'mr.bob.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mr.bob.egg-info\SOURCES.txt'
    creating build\lib\mrbob\template_sample
    copying mrbob\template_sample\.mrbob.ini -> build\lib\mrbob\template_sample
    copying mrbob\template_sample\sample.txt.bob -> build\lib\mrbob\template_sample
    creating build\lib\mrbob\template_starter
    copying mrbob\template_starter\.mrbob.ini -> build\lib\mrbob\template_starter
    copying mrbob\template_starter\sample.txt.bob -> build\lib\mrbob\template_starter
    copying mrbob\tests\example.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example2.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example3.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example4.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example5.ini -> build\lib\mrbob\tests
    copying mrbob\tests\example6.ini -> build\lib\mrbob\tests
    copying mrbob\tests\ignored.ini -> build\lib\mrbob\tests
    copying mrbob\tests\ignored_dirs.ini -> build\lib\mrbob\tests
    copying mrbob\tests\question_order.ini -> build\lib\mrbob\tests
    copying mrbob\tests\unbound.ini -> build\lib\mrbob\tests
    creating build\lib\mrbob\tests\templates
    copying mrbob\tests\templates\strict_undefined.bob -> build\lib\mrbob\tests\templates
    creating build\lib\mrbob\tests\templates\ask_hooks
    copying mrbob\tests\templates\ask_hooks\.mrbob.ini -> build\lib\mrbob\tests\templates\ask_hooks
    creating build\lib\mrbob\tests\templates\ds_store
    copying mrbob\tests\templates\ds_store\.DS_Store -> build\lib\mrbob\tests\templates\ds_store
    copying mrbob\tests\templates\ds_store\.mrbob.ini -> build\lib\mrbob\tests\templates\ds_store
    creating build\lib\mrbob\tests\templates\empty
    copying mrbob\tests\templates\empty\.mrbob.ini -> build\lib\mrbob\tests\templates\empty
    creating build\lib\mrbob\tests\templates\empty2
    copying mrbob\tests\templates\empty2\.mrbob.ini -> build\lib\mrbob\tests\templates\empty2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\krl91\AppData\Local\Temp\pip-build-exg5brph\mr.bob\setup.py", line 79, in <module>
        zip_safe=False,
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\build_py.py", line 53, in run
        self.build_package_data()
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\build_py.py", line 121, in build_package_data
        self.mkpath(os.path.dirname(target))
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 338, in mkpath
        dir_util.mkpath(name, mode, dry_run=self.dry_run)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\dir_util.py", line 66, in mkpath
        log.info("creating %s", head)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\log.py", line 44, in info
        self._log(INFO, msg, args)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\distutils\log.py", line 34, in _log
        stream.write('%s\n' % msg)
      File "c:\users\krl91\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u030c' in position 50: character maps to <undefined>`

**Comment by jmilun** [comment]
I have set the Windows environment variable PYTHONIOENCODING to UTF-8 (on Windows 7: "Control Panel"-> "System" -> "Advanced system settings" -> "Advanced" -> Environment Variables ..."). It solved the problem. I hope it will do for you as well.

**Comment by krl91** [comment]
Thanks
